version: "3.7"

services:
  project-zomboid:
    image: afey/zomboid
    container_name: Project-Zomboid
    restart: unless-stopped
    environment:
      SERVER_NAME: "pzserver"
      ADMIN_PASSWORD: "pzserver-password"
    ports:
      - "8766:8766/udp"
      - "8767:8767/udp"
      - "16261:16261/udp"
      - "16262-16272:16262-16272"
      - "27015:27015"
    volumes:
      - /docker-server-data/project-zomboid/server-data:/server-data
      - /docker-server-data/project-zomboid/server-files:/server-files
